### ISSUE TITLE
Submit a job  failed

### ISSUE THREAD

**Issue by chenzhe** [daxnet/abacuza#20]
stdout: 
21/09/03 09:17:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported spark version used: 3.1.2. Normalized spark version used: 3.1.2. Supported versions: 3.0.0, 3.0.1
	at org.apache.spark.deploy.dotnet.DotnetRunner$.validateSparkVersions(DotnetRunner.scala:172)
	at org.apache.spark.deploy.dotnet.DotnetRunner$.main(DotnetRunner.scala:46)
	at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/09/03 09:17:24 INFO ShutdownHookManager: Shutdown hook called
21/09/03 09:17:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-f4594dd6-4678-47c9-a142-f61d2161f4a4
21/09/03 09:17:24 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
21/09/03 09:17:24 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
21/09/03 09:17:24 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.

stderr:

**Comment by daxnet** [comment]
@chenzhe 
Is it possible to provide detailed steps to reproduce this issue? It will be better if you could send me the source code of your job runner.
Thank you.

**Comment by chenzhe** [comment]
是jar 包版本问题，上传错了要上传3.1.*的

**Comment by daxnet** [comment]
@chenzhe 
好的，多谢反馈。
